// French translations for exercise cards
// Keyed by exercise ID

export type ExFr = {
  description: string
  steps: [string, string, string]
  levels: { novice: string; beginner: string; intermediate: string; advanced: string; elite: string }
}

export const MUSCLE_FR: Record<string, string> = {
  'Back & Biceps': 'Dos & Biceps',
  'Biceps & Back': 'Biceps & Dos',
  'Lats': 'Grand dorsal',
  'Mid Back': 'Dos moyen',
  'Full Posterior Chain': 'Chaîne postérieure complète',
  'Hamstrings & Glutes': 'Ischio-jambiers & Fessiers',
  'Biceps': 'Biceps',
  'Brachialis & Biceps': 'Brachial & Biceps',
  'Long Head Biceps': 'Chef long biceps',
  'Brachialis & Forearms': 'Brachial & Avant-bras',
  'Rear Delts': 'Deltoïdes postérieurs',
  'Lats & Rhomboids': 'Grand dorsal & Rhomboïdes',
  'Mid & Lower Back': 'Dos moyen & Lombaires',
  'Rear Delts & Traps': 'Deltoïdes post. & Trapèzes',
  'Chest': 'Pectoraux',
  'Upper Chest': 'Pectoraux supérieurs',
  'Chest (stretch)': 'Pectoraux (étirement)',
  'Chest & Triceps': 'Pectoraux & Triceps',
  'Triceps': 'Triceps',
  'Shoulders': 'Épaules',
  'Full Deltoid': 'Deltoïdes complets',
  'Medial Deltoid': 'Deltoïde médial',
  'Anterior Deltoid': 'Deltoïde antérieur',
  'Triceps & Chest': 'Triceps & Pectoraux',
  'Long Head Triceps': 'Chef long triceps',
  'Lower Chest': 'Pectoraux inférieurs',
  'Chest (inner)': 'Pectoraux (interne)',
  'Quads & Glutes': 'Quadriceps & Fessiers',
  'Quads': 'Quadriceps',
  'Glutes': 'Fessiers',
  'Hamstrings': 'Ischio-jambiers',
  'Calves': 'Mollets',
  'Core': 'Gainage',
  'Upper Abs': 'Abdos supérieurs',
  'Obliques': 'Obliques',
  'Lower Abs & Hip Flexors': 'Abdos inf. & Fléchisseurs hanche',
  'Core & Cardio': 'Gainage & Cardio',
  'Full Core': 'Gainage complet',
  'Obliques & Core': 'Obliques & Gainage',
  'Deep Core': 'Gainage profond',
  'Full Body': 'Corps entier',
  'Legs & Explosiveness': 'Jambes & Explosivité',
  'Core & Hip Flexors': 'Gainage & Fléchisseurs hanche',
  'Upper Body & Core': 'Haut du corps & Gainage',
  'Glutes & Cardio': 'Fessiers & Cardio',
  'Legs & Cardio': 'Jambes & Cardio',
  'Full Body Core': 'Gainage corps entier',
  'Full Body & Cardio': 'Corps entier & Cardio',
  'Legs & Core': 'Jambes & Gainage',
  'Biceps Peak': 'Pic du biceps',
  'Chest & Explosiveness': 'Pectoraux & Explosivité',
  'Full Body & Coordination': 'Corps entier & Coordination',
  'Glutes & Adductors': 'Fessiers & Adducteurs',
  'Obliques & Abs': 'Obliques & Abdos',
  'Quads & Core': 'Quadriceps & Core',
  'Shoulders & Chest': 'Épaules & Pectoraux',
  'Lats & Mid Back': 'Grand dorsal & Dos moyen',
  'Mid Back & Traps': 'Dos moyen & Trapèzes',
  'Mid Back & Rhomboids': 'Dos moyen & Rhomboïdes',
  'Biceps & Forearms': 'Biceps & Avant-bras',
  // ── New Life Fitness machine muscles ──
  'Lats & Biceps': 'Grand dorsal & Biceps',
  'Upper Back & Traps': 'Dos supérieur & Trapèzes',
  'Lower Back & Erectors': 'Lombaires & Érecteurs',
  'Shoulders & Triceps': 'Épaules & Triceps',
  'Medial Deltoids': 'Deltoïdes médiaux',
  'Chest (Inner & Stretch)': 'Pectoraux (interne & étirement)',
  'Rectus Abdominis': 'Droit abdominal',
  'Rectus Abdominis & Core': 'Droit abdominal & Gainage',
  'Quads, Glutes & Hamstrings': 'Quadriceps, Fessiers & Ischio-jambiers',
  'Glutes & Hip Abductors': 'Fessiers & Abducteurs de hanche',
  'Calves (Gastrocnemius & Soleus)': 'Mollets (Gastrocnémien & Soléaire)',
  'Lower Back, Glutes & Hamstrings': 'Lombaires, Fessiers & Ischio-jambiers',
  'Full Body Activation': 'Activation corps entier',
  'Cardio & Legs': 'Cardio & Jambes',
  'Legs & Cardiovascular': 'Jambes & Cardiovasculaire',
  'Cardio & Fat Metabolism': 'Cardio & Métabolisme lipidique',
}

export const EQUIP_FR: Record<string, string> = {
  'Bar': 'Barre fixe',
  'Barbell': 'Barre',
  'Cable Machine': 'Poulie',
  'Dumbbell': 'Haltères',
  'Bodyweight': 'Poids du corps',
  'Machine': 'Machine',
  'Machine/Bodyweight': 'Machine / Poids du corps',
  'Ab Wheel': 'Roue abdominale',
  'Ropes': 'Cordes',
  'Box': 'Box',
  'Jump Rope': 'Corde à sauter',
  'Bike': 'Vélo',
  'Stairs': 'Escaliers',
  'Rowing Machine': 'Rameur',
  'None': 'Aucun',
  'Kettlebell': 'Kettlebell',
  'Bars': 'Barres',
  // ── Life Fitness machines ──
  'Life Fitness Machine': 'Machine Life Fitness',
  'Life Fitness Treadmill': 'Tapis Life Fitness',
  'Life Fitness Bike': 'Vélo Life Fitness',
}

export const EXERCISE_FR: Record<number, ExFr> = {}
