import 'dotenv/config'
import { PrismaClient } from '../app/generated/prisma/client'

const db = new PrismaClient()

const tips = [
  // ── MECHANICS (15) ────────────────────────────────────────────────────────
  { category:'MECHANICS', title:'Crosshair Placement at Head Level', agent:null,
    content:`Always keep your crosshair at head height as you move around the map. Most players aim at chest or ground level, meaning they need to adjust upward before shooting — you don't. This single habit cuts your time-to-kill by removing the flick adjustment entirely.\n\nKeep your crosshair "floating" at head height even in empty corridors. Your eyes will train to track that level instinctively over time.`,
    drill:`In deathmatch, ban yourself from shooting any bullet that requires a downward flick. Only shoot when your crosshair is already on the head. Refuse the shot otherwise. Do this for 15 minutes daily for 2 weeks.` },
  { category:'MECHANICS', title:'Counter-Strafing Before Shooting', agent:null,
    content:`Rifles in Valorant have near-zero accuracy while moving. You must come to a full stop before your first bullet lands on target. Counter-strafe by tapping the opposite direction key (holding A → tap D) to cancel momentum instantly.\n\nThe accuracy recovery window is ~100–150ms after stopping. Without counter-strafing, you slide for an additional 200–300ms and all bullets spray randomly.`,
    drill:`In the shooting range, set enemies to moving. Walk toward each target, counter-strafe to stop, then shoot. If you miss the head on first bullet, your counter-strafe was too slow. Repeat 200 reps.` },
  { category:'MECHANICS', title:'Wide Peek vs Tight Peek', agent:null,
    content:`A wide peek gives you more time to react to the enemy's model before they can react to yours — you see them first. A tight peek minimizes your exposed hitbox at the cost of reaction time.\n\nUse wide peeks against players holding passive angles (AWPers, Operators). Use tight peeks when you expect aggressive pushes or pre-aim.`,
    drill:`In customs, ask a friend to hold a static angle on Haven A-long. Practice wide peeking that corner 20 times. Time how long between you seeing them and them seeing you — aim to get a 0.15s+ gap.` },
  { category:'MECHANICS', title:'Jiggle Peeking for Information', agent:null,
    content:`Quickly expose your hitbox and return to cover without fully committing to a peek. This forces opponents to react (revealing their aim position and utility usage) while you take almost zero damage if they're unprepared.\n\nThe key is speed — the peek must be under 0.3 seconds. Anything slower becomes a real peek and you take the duel.`,
    drill:`Stand at B-main on Bind. Jiggle toward B-site 30 times. Your goal: spot defender positions without dying once. Count how many times you gather info successfully versus how many times you get hit.` },
  { category:'MECHANICS', title:'Spray Control Patterns', agent:null,
    content:`After the first 4 accurate bullets, every rifle develops a predictable spray pattern — mostly upward then left/right. Pull your mouse down and slightly to the left (for Vandal/Phantom) to compensate. The pattern resets if you stop firing for 0.6s.\n\nDon't learn spray patterns theoretically — muscle memory is built through thousands of repetitions, not study.`,
    drill:`10 minutes every session in the shooting range: fire full magazines at a close wall. Watch the pattern, pull down to keep bullets centered. Do this until all 30 bullets fit within a head-sized circle at 10m.` },
  { category:'MECHANICS', title:'Crouch Discipline — Never Mid-Fight', agent:null,
    content:`Crouching mid-fight is a trap. Crouching improves accuracy but slows movement drastically. Against experienced players, crouching mid-duel makes you an easier target — they track your head down as you lower.\n\nCrouch only when already stationary and behind cover as an initial position. Never crouch reactively in an active gunfight.`,
    drill:`Play a full deathmatch session with one rule: you cannot press crouch at all. Notice your instinct to press it when stressed. Breaking this habit forces you to counter-strafe instead.` },
  { category:'MECHANICS', title:'One-Tapping on Pistol Rounds', agent:null,
    content:`The Classic and Sheriff reward headshots disproportionately. A single headshot from Classic kills at close range. On pistol round, skip body-spraying entirely — click once at head level, wait for reset (0.5s), click again.\n\nPistol round is won by one-tap discipline, not aim speed. Slow down your click rate by 50% and your headshot rate will spike.`,
    drill:`Pistol-only deathmatch for 15 minutes using only Classic or Ghost. Force yourself to only fire once per "burst" with a deliberate pause between clicks. Track headshot percentage — target above 30%.` },
  { category:'MECHANICS', title:'Pre-Firing Common Angles', agent:null,
    content:`Most players hold the same 4–5 spots on every site every round. Instead of peeking reactively, prefire these positions as you walk around the corner. Your bullets arrive before your visual confirms them.\n\nBuilding prefire muscle memory takes 2–3 sessions per map but saves you countless duels per game.`,
    drill:`Solo custom on Ascent: walk through B-main to B-site and prefire every known defensive spot (market window, B-short boxes, B-site default) without seeing anyone. Build the muscle memory of the angles.` },
  { category:'MECHANICS', title:'Flick Shot Technique — Wrist vs Arm', agent:null,
    content:`Short flicks (sub-30cm on screen) should be wrist-driven. Long flicks use arm movement. Mixing them causes overshoots. Train each separately.\n\nFlick accuracy degrades at high sensitivity — most top players use 800 DPI with 0.3–0.4 in-game. Lower sens teaches arm movement and gives finer micro-adjustments.`,
    drill:`In Aim Lab or KovaaK, run Gridshot for 10 minutes focusing only on wrist micro-adjustments. Next 10 minutes, run a wide-spread scenario forcing arm flicks. Never mix the two in a single drill.` },
  { category:'MECHANICS', title:'Audio Discipline — Shift-Walk Timing', agent:null,
    content:`Your footsteps are heard by opponents within 40m. Walking speed (Shift held) is completely silent. Use it aggressively during repositions — after planting the spike, rotating through mid, or flanking.\n\nMost players walk too rarely. A good habit: shift-walk any time you're within 2 rooms of a known enemy position.`,
    drill:`Play a full game muted (no music, no voice chat) and focus only on listening. Count how many times enemy footsteps revealed their position before you saw them. Actively shift-walk whenever you know they're close.` },
  { category:'MECHANICS', title:'Off-Angle Positioning', agent:null,
    content:`Off-angles are positions your opponent doesn't expect — slightly above, slightly to the side, or behind from where the crosshair would naturally rest. A 20cm shift from a common spot becomes unpredictable.\n\nOff-angles work once. If you use the same off-angle 3 rounds in a row, it becomes a common angle.`,
    drill:`On defense, play 5 rounds holding only off-angles — not the standard boxes or corners. If you die, pick a new spot next round. Track how many rounds your off-angle catches someone off-guard vs. how many times you die to a prefire.` },
  { category:'MECHANICS', title:'Spray Transfer Between Targets', agent:null,
    content:`When you eliminate a target mid-spray, your spray pattern doesn't reset. You must account for accumulated recoil when transferring to the next enemy. Briefly counter-spray (pull down the continued offset) while moving to the next target.\n\nMost players spray-transfer at head height and miss because recoil has pulled their crosshair off pattern.`,
    drill:`In the shooting range, set 3 enemies in a line. Practice spraying 6 bullets into target 1, then transferring to target 2 and continuing the pull-down. Spray-transfer accuracy is what separates mid-Elo from high-Elo mechanics.` },
  { category:'MECHANICS', title:'Burst Firing at Distance', agent:null,
    content:`At 30m+ range, spraying is inaccurate even with full recoil compensation. Burst fire: 3 bullets, 0.5s pause, 3 bullets. Each burst resets the spray pattern and your bullets stay on target.\n\nVandal bursting is stronger than Phantom at distance because Vandal has full damage at any range.`,
    drill:`Shooting range, long-range mode. Fire only 3-bullet bursts with a deliberate pause between each. Count consecutive headshots. Target: 5 consecutive head-bursts before moving to medium range.` },
  { category:'MECHANICS', title:'Knife Cancel for Silent Repositioning', agent:null,
    content:`Switching to your knife stops your sprint animation and gives you silent movement faster than weapon-walk. Use knife + shift-walk during mid-round rotations for maximum speed with zero audio footprint.\n\nKnife movement speed is ~6.75 m/s vs rifle walk at ~3.5 m/s. Never rotate mid-round holding your primary.`,
    drill:`In a custom game, time your rotation from A-site to B-site on Bind: (1) rifle walk, (2) knife-run + shift-walk. Compare times. Train this as a default habit — knife out any time you rotate more than 15m.` },
  { category:'MECHANICS', title:'Peek Timing Variance', agent:null,
    content:`Predictable timing gets you killed by experienced players who prefire your peek. Vary your peek timing: sometimes peek at 1s, sometimes at 4s. The unpredictability forces opponents to actively hold rather than passively prefire.\n\nA peek at t=3.7s is almost un-prefirable; a peek at exactly t=1.0s every time gets you killed in Diamond+.`,
    drill:`Solo custom on Ascent. Hold A-main and have a bot set to prefire the corner every 1.5 seconds. Practice varying your peek timing until the bot cannot prefire you consistently. Then bring this into ranked.` },

  // ── STRATEGY (15) ──────────────────────────────────────────────────────────
  { category:'STRATEGY', title:'Default Before Executing', agent:null, drill:null,
    content:`Spend the first 40 seconds of each attack round playing default — spreading the map, gathering info, and playing picks. Only after establishing info should you commit to an execute. The best executes are built on confirmed defender positions.\n\nThe biggest mistake at low-mid Elo is force-executing at 0 seconds with zero information. Default play wins rounds before the execute even starts.` },
  { category:'STRATEGY', title:'Fake Executes to Force Rotations', agent:null, drill:null,
    content:`Deploy full site utility on A — smokes, flashes, molotovs — and call out an A execute. Two players burn utility to make it believable, then hard rotate to B. Defenders commit to A and have no time to rotate.\n\nFakes only work if the commitment is real enough. Half-hearted fakes are read immediately. Go to the edge of commitment.` },
  { category:'STRATEGY', title:'Mid Control Wins the Map', agent:null, drill:null,
    content:`Whoever controls mid controls rotations. From mid, defenders can reach either site in 3–4 seconds, while attackers must commit one direction. Winning mid control turns a 5v5 into an overwhelming advantage on either site.\n\nOn Ascent, Haven, and Bind, mid control is so valuable that it's worth sending 2 players specifically to contest it every round.` },
  { category:'STRATEGY', title:'First Blood Win Rate — 72% Rule', agent:null, drill:null,
    content:`Teams that get first blood win the round approximately 70–72% of the time. This is the single highest-impact statistic in Valorant. Structure your early game around trading kills favorably, not around dying for information.\n\nChallenge: every round, identify the single most likely first-blood duel and position your best fragger to win it.` },
  { category:'STRATEGY', title:'Lurk Timing — Cut the Rotation', agent:null, drill:null,
    content:`A lurker's job is to watch the rotation path and kill defenders as they rotate. If your team is executing A, the lurker should be watching Mid and B-short — exactly where defenders will rotate through.\n\nLurk timing: delay 5–8 seconds after your team initiates contact on site. Defenders will rotate at that point and walk into you.` },
  { category:'STRATEGY', title:'Anti-Eco Positioning', agent:null, drill:null,
    content:`On eco rounds, don't over-peek or play aggressive. Opponents have pistols and SMGs — they lose to rifles in open duels but win in close range. Play slow, let them come to you, and use your rifle advantage at distance.\n\nBiggest mistake on "free rounds": dying to a Ghost headshot by walking into a close-range duel.` },
  { category:'STRATEGY', title:'Post-Plant Positioning', agent:null, drill:null,
    content:`After planting the spike, your team should be in: (1) crossfire positions covering the defuse, (2) off-angles that retakers won't expect, (3) utility saved for the retake, not the execute.\n\nLearn 2–3 post-plant spots per site on every map you play. These spots are often more important than execute lineups.` },
  { category:'STRATEGY', title:'Retake Protocol — Coordination First', agent:null, drill:null,
    content:`Don't retake at full speed — you'll die to crossfires. Instead: (1) hold outside until 20 seconds remain, (2) gather everyone, (3) coordinate smokes, flashes, and molotovs, then (4) push together on the count.\n\nA synchronized retake with utility clears beats a faster uncoordinated rush every time.` },
  { category:'STRATEGY', title:'Ultimate Economy Management', agent:null, drill:null,
    content:`Ults are strongest when used together. Coordinate with your team to save ults for the same round — a round where you're losing economically but want to force a win. One well-timed combined ult can break a loss streak.\n\nNever waste ults on rounds you're already winning by 3+ kills.` },
  { category:'STRATEGY', title:'Stack Reading — Predict Site Preference', agent:null, drill:null,
    content:`After round 3–4, start tracking which site each opponent prefers. If 3 of 5 attackers hit B three rounds straight, their IGL defaults to B. Call a stack (send 3–4 defenders to B) before the round starts.\n\nStack reads are probabilistic — they fail sometimes. But over a half, correct stacks win you 2–3 "free" rounds.` },
  { category:'STRATEGY', title:'Half-Time Adaptation', agent:null, drill:null,
    content:`The first half is scouting. At half-time, note: (1) which utility they burned on each execute, (2) which lurker they use and their timing, (3) their preferred site. Then anti-strat it in the second half.\n\nTeams that win in ranked rarely have better mechanics than opponents — they adapt faster.` },
  { category:'STRATEGY', title:'Slow vs Fast Execute', agent:null, drill:null,
    content:`Fast execute: all 5 rush a site in 0 seconds with minimal utility. Beats defenders who are still rotating or playing passive. Slow execute: spend 20–30 seconds clearing entry angles one by one with utility. Beats defenders who are fully set up.\n\nRead the round: if you got early info that defenders are stacked, fast execute. If no info, slow methodical execute.` },
  { category:'STRATEGY', title:'Trading Discipline', agent:null, drill:null,
    content:`When your teammate peeks and dies, your only job is to immediately trade that kill — even if you might die too. A 1-for-1 trade keeps the round even. Letting kills go un-traded creates a numbers disadvantage that compounds.\n\nPosition your second player 1–2 meters behind the first, ready to prefire the position that got the kill.` },
  { category:'STRATEGY', title:'Timing Synchronization on Executes', agent:null, drill:null,
    content:`Staggered executes fail against organized defense. If Player 1 enters 0.5s before Player 2, defenders kill Player 1 then pre-aim Player 2. All 5 should step onto site within a 0.5-second window.\n\nUse a verbal count: "Execute in 3... 2... 1... GO." Practice this until team timing becomes instinctive.` },
  { category:'STRATEGY', title:'Info Before Committing — No Free Deaths', agent:null, drill:null,
    content:`Never die without giving your team something: a callout, utility used, a rotation forced. If you're about to push aggressively with no information and no plan to trade, wait. Patience is information.\n\nAsk yourself before every peek: "What does my team gain if I die here?" If the answer is nothing, don't peek.` },

  // ── MINDSET (15) ──────────────────────────────────────────────────────────
  { category:'MINDSET', title:'Warmup Routine Before Ranked', agent:null,
    content:`20 minutes of deathmatch + 10 minutes in the shooting range activates your aim and game-sense before your rank is on the line. Cold queuing (going straight to ranked) is the leading cause of 0–5 starts that snowball into loss streaks.\n\nA warmup session doesn't need to be perfect — it just needs to get your brain and hands in sync before the score counts.`,
    drill:`Fixed warmup: 15 min unrated DM (aim for 25+ kills), 5 min range (spray patterns), then queue. Track your round win rate in the first 3 rounds of ranked before and after implementing this routine.` },
  { category:'MINDSET', title:'The Two-Loss Rule', agent:null, drill:null,
    content:`After 2 consecutive ranked losses, stop queuing for at least 20 minutes. The emotional state after back-to-back losses is measurable — cognitive function drops, reaction time slows, decision-making regresses.\n\nEvery loss you play while tilted adds to the next loss's emotional weight. The two-loss rule breaks the cycle before it starts.` },
  { category:'MINDSET', title:'VOD Review — Watch Your 3 Worst Deaths', agent:null,
    content:`After a loss, don't watch your best clips. Watch your 3 worst deaths. For each, ask: (1) what info did I not have? (2) what decision led me into that position? (3) what would have been the better play?\n\nHighlight reels reinforce ego. Death reviews reinforce improvement.`,
    drill:`After every ranked game, rewatch your 3 cheapest-feeling deaths. Write one sentence per death: what you should have done differently. Accumulate this into a personal error log. Review monthly.` },
  { category:'MINDSET', title:'Focus on Your Own Game', agent:null, drill:null,
    content:`You cannot control your teammates. You can control your positioning, your utility usage, your comms, and your mechanics. Mentally, every round is a personal test — did YOU play that correctly?\n\nPlayers who focus on self-improvement climb steadily. Players who blame teammates stay stuck at the same rank for years.` },
  { category:'MINDSET', title:'Tilt Recognition Checklist', agent:null, drill:null,
    content:`You are tilted if you notice: (1) rushing corners you normally play patiently, (2) not communicating or calling out, (3) playing aggressively after dying, (4) muting teammates. These are physiological stress responses, not tactical choices.\n\nThe moment you recognize tilt, say out loud: "I'm tilted." That metacognition alone reduces its effect significantly.` },
  { category:'MINDSET', title:'Rank Is a Lagging Indicator', agent:null, drill:null,
    content:`Your rank reflects your average performance from 2–4 weeks ago. If you've improved this week, your rank hasn't caught up yet. Stop using rank to measure your current skill.\n\nInstead, track leading indicators: average damage per round, first-blood duels won, utility efficiency. Rank follows these, not the other way around.` },
  { category:'MINDSET', title:'Volume vs Quality Sessions', agent:null, drill:null,
    content:`3 focused, intentional ranked games produce more growth than 8 frustrated games. Each game should have a single mechanical focus (e.g., "today I'm only working on counter-strafe timing"). When you're no longer focused on the target skill, stop playing.\n\nQuality = awareness during play. The moment you're on autopilot, the session's value drops to zero.` },
  { category:'MINDSET', title:'Positive Communication Style', agent:null, drill:null,
    content:`"Good try" after a failed execute keeps team morale higher than silence. "Reset and info-play next round" after a loss gives direction. You don't have to be a cheerleader — just replace blame-language with action-language.\n\nTeams with positive communication win 8–12% more rounds on equal skill level. Comms is a trainable skill.` },
  { category:'MINDSET', title:'Ego Peeking — When to Hold', agent:null, drill:null,
    content:`You're up 2v1 and winning the round. This is not the time to push — it's time to hold and let the opponent come to you. Ego peeking in a winning position turns a guaranteed round win into a potential 1v1 or even loss.\n\nRule: when you're ahead in numbers, let time and position work for you. Force them to take the risky play.` },
  { category:'MINDSET', title:'Variance Acceptance', agent:null, drill:null,
    content:`Approximately 25–30% of rounds in any match are lost to pure variance: a pixel-perfect spam through a wall, a random spray one-tap, a connection issue. These rounds are unwinnable. Do not review them, do not carry them emotionally.\n\nThe mental skill is distinguishing "I made a bad decision" from "that was variance." Get fast at telling the difference.` },
  { category:'MINDSET', title:'Single Focus Per Session', agent:null, drill:null,
    content:`Trying to improve everything simultaneously improves nothing. Pick one skill per session: today is counter-strafe day. Tomorrow is crosshair placement day. Next session is lurk timing.\n\nWhen your focus skill clicks — when you do it automatically without thinking — it's internalized. Move to the next one.` },
  { category:'MINDSET', title:'Pre-Game Physical Checklist', agent:null, drill:null,
    content:`Before queuing ranked: (1) full water glass within reach, (2) posture check — sit straight, (3) monitor brightness adjusted, (4) 5 slow deep breaths, (5) clear your phone away. These 3 minutes of preparation measurably improve first-round performance.\n\nPhysical state directly impacts reaction time and decision speed. Treat pre-game prep like a professional.` },
  { category:'MINDSET', title:'Meta Adaptation Cycle', agent:null, drill:null,
    content:`Every major patch shifts the meta. If you haven't watched pro play or updated your agent pool in 6+ weeks, you're behind. One session of VCT highlights per week is enough to stay current.\n\nSpecific meta reads: track which agents are picked in 3+ consecutive pro rounds — those are the current meta cores.` },
  { category:'MINDSET', title:'Learning from Every Death', agent:null, drill:null,
    content:`Reframe every death with one question: "What information did I lack that caused this?" Not "why did they headshot me" but "why did I peek into a position where they could headshot me?" The second question is answerable and actionable.\n\nThis reframe turns frustration into curiosity — and curious players improve faster than frustrated ones.` },
  { category:'MINDSET', title:'The 1% Daily Improvement Rule', agent:null, drill:null,
    content:`A 1% daily improvement compounds powerfully over months. The maths don't matter — the point is that tiny, consistent daily improvements outperform large sporadic ones every time.\n\nYour only daily benchmark: "Was I slightly more intentional today than yesterday?" Yes = success. That's the entire system.` },

  // ── AGENT (15) ─────────────────────────────────────────────────────────────
  { category:'AGENT', agent:'Jett', title:'Jett — Dash Direction with Right-Click',
    content:`Jett's Tailwind (dash) travels in the direction you're moving, not where you're aiming. Right-clicking before a dash lets you "store" the ability and dash on release — perfect for the classic dash-to-shoulder-peek or peek-op-dash-back.\n\nAdvanced: bind dash to a side mouse button so you can fire and dash simultaneously without using the same hand.`,
    drill:`In customs, practice the Operator dash peek 50 times on Ascent A-main: peek with op, shoot or miss, immediately dash back to safety. Target: consistently retreat behind the box within 0.4s of peeking.` },
  { category:'AGENT', agent:'Sage', title:'Sage — Sloworb on the Spike Post-Plant',
    content:`Place a Sage sloworb directly on the spike before you plant. On defuse attempts, the defender walks into the orb and is slowed by 65% — your crossfire kills them before they can defuse or dodge.\n\nThis is among the strongest post-plant utility in the game and is available even on eco rounds. Learn the orb placement for every plant zone on every map you play.`,
    drill:`Custom game: practice placing sloworbs directly on default plant spots on Bind, Ascent, and Split. A well-placed orb covers the entire defuse radius. The slow takes ~1.5s to apply — throw it slightly before enemies arrive.` },
  { category:'AGENT', agent:'Omen', title:'Omen — One-Way Smokes on Key Angles',
    content:`Omen's smokes can be positioned to cover enemy sightlines while leaving a tiny gap at ankle or knee level — a "one-way." Your teammates shoot through the gap; enemies can't see through the smoke in return.\n\nKey one-ways: Bind B-site (smoke back-of-site box with ankle gap toward B-main), Ascent A-site (market window), Haven C-site (default box).`,
    drill:`In customs, spend one hour finding one-way smoke positions on Bind. Goal: a smoke that completely covers enemy head at their default position while leaving a sub-knee-level line of sight from your side.` },
  { category:'AGENT', agent:'Killjoy', title:'Killjoy — Nanoswarm Under the Spike',
    content:`Before planting, place a Nanoswarm grenade directly under the spike's intended plant spot. After planting, the grenade is invisible and overlapped by the spike model. Activate it the moment you see the defuse — guarantees damage or a kill.\n\nPair with a Lockdown or Turret for a full post-plant package that can hold a 1v3.`,
    drill:`Solo custom on Bind: practice placing nanoswarm under B-default spike, planting, then running to post-plant cover. Activate the swarm at 35 seconds on the clock (typical defuse start time). Adjust timing until swarm covers the full defuse window.` },
  { category:'AGENT', agent:'Reyna', title:'Reyna — Dismiss Timing for Max Survivability',
    content:`Dismiss (E) becomes Devour if you're not full HP and Dismiss if you are. After a kill, wait for an overheal orb from Devour before using Dismiss — enter the next duel with 150HP.\n\nAdvanced: Dismiss doesn't need to be used for escape. Use it to reposition aggressively into a better angle on the same target's teammates.`,
    drill:`Deathmatch session: practice the kill → Devour → Dismiss → peek cycle. Train the timing where you pick up at least 50HP from Devour before dismissing. Track how many dismisses you use for repositioning vs retreating.` },
  { category:'AGENT', agent:'Phoenix', title:'Phoenix — Curveball Flash Around Corners',
    content:`Phoenix's Curveball curves in the direction of the throw. Right-click curves left; left-click curves right. Thrown correctly around a corner, it flashes everyone in the next room without self-blinding.\n\nKey timing: throw the flash so it detonates after it's around the corner. If thrown too early, opponents see it coming and look away.`,
    drill:`In a custom game, practice Phoenix flashing Bind A-short → A-site. Stand at the corner, right-click curve the flash tightly around the wall. It should pop on-site without you seeing it. Get this timing consistent before using in ranked.` },
  { category:'AGENT', agent:'Sova', title:'Sova — Two Lineups Per Site Per Map',
    content:`You don't need every Sova lineup. You need 2 reliable recon bolt lineups per site on your main 3 maps. That's 12–18 lineups total — a few hours to learn, a permanent advantage. These lineups reveal more defender positions than any other ability in the game.\n\nPrioritize: default plant area reveal, and one that clears common off-angle positions.`,
    drill:`Spend 2 custom-game sessions learning 2 Recon Bolt lineups per site on Ascent (A and B). Then spend 1 session drilling them from memory until you can hit both with your eyes closed on demand.` },
  { category:'AGENT', agent:'Viper', title:'Viper — Toxic Screen Timing Delay',
    content:`Don't deploy Toxic Screen immediately at round start on attack. Deploying early shows the defender exactly which site you're hitting. Deploy it 2–3 seconds after your team starts the attack.\n\nThe 2-second delay means defenders have already committed to their rotation decision — and now they're stuck on the wrong side of the screen.`,
    drill:null },
  { category:'AGENT', agent:'Breach', title:'Breach — Fault Line Through Walls',
    content:`Fault Line (Q) and Aftershock (C) go through walls. 95% of Breach's value comes from utility deployed through terrain, not through open space. Learn which walls on your map are Breach-penetrable and stun defenders before your team peeks.\n\nBreach is one of the strongest initiators precisely because he doesn't need sightlines — but only if you know the wall geometry.`,
    drill:`In a custom, spend 30 minutes on Haven finding every wall that Fault Line penetrates: through garage wall to CT, through A-lobby wall to A-long, through C-garage. Map these out before your first ranked game as Breach.` },
  { category:'AGENT', agent:'Cypher', title:'Cypher — Tripwire + Cage Synergy',
    content:`Place a Cyber Cage directly over a Tripwire. When an enemy triggers the wire, they're blinded by the cage (if you activate it) and revealed simultaneously. This gives you a perfectly timed kill setup — they're revealed, slowed, and blinded at the same point.\n\nThe combination beats any 1v1 duel in Cypher's favor even against better aimers.`,
    drill:`In a custom, set up the Tripwire + Cage combo on Bind B-short. Have a friend walk through while you watch the flank. Practice activating the cage the instant the wire triggers. Time your crossfire prefire to match the activation.` },
  { category:'AGENT', agent:'Raze', title:'Raze — Double-Satchel Movement',
    content:`The first satchel grounds you (stops fall momentum). The second launches you. Together they create Raze's signature rocket-jump movement. The key: throw the first satchel at the ground directly below you, then the second at a 45° angle toward your target direction.\n\nPractice this until both satchels fire in under 0.8 seconds — slower double-satchels are predictable and get you killed mid-flight.`,
    drill:`Custom on Ascent: double-satchel from A-main onto A-site boxes. Target: land on the box, not fall off it. Practice 30 reps. Then learn the Bind B-main to B-site elevation gain double-satchel.` },
  { category:'AGENT', agent:'Skye', title:'Skye — Trailblazer + Flash Combo Timing',
    content:`Send Trailblazer (wolf) into a site first. The moment it spots an enemy (you see the player model in the dog's view), immediately throw Guiding Light (flash) into that same space. Enemies who reacted to the dog will have their eyes on it and get flashed.\n\nThe combo works because enemies can't simultaneously dodge the dog AND look away from the flash.`,
    drill:`Custom: send Trailblazer into A-site on Bind while a friend plays defender. Practice the exact timing of throwing Guiding Light the instant the Trailblazer makes contact — not before, not after. Aim for under 0.3s delay.` },
  { category:'AGENT', agent:'Chamber', title:'Chamber — TP Anchor Placement',
    content:`Place your Rendezvous TP anchor behind solid cover with clear sightlines to 1–2 common peek angles. The TP only saves you if the landing zone is safe. Many Chamber players die because they TP into the open or onto a spot that's already been pushed.\n\nRule: if you can't shoot from your TP landing spot immediately, find a different anchor placement.`,
    drill:null },
  { category:'AGENT', agent:'Astra', title:'Astra — Gravity Well + Nebula Cancel Trick',
    content:`After activating Gravity Well (which groups enemies), immediately recall it and replace with a Nebula smoke in the exact same location. Enemies pulled by the gravity well are now stuck inside a smoke with no vision.\n\nThis combo essentially forces a 5v4 equivalent on any site execute — enemies in the smoke can't see or be traded by defenders outside.`,
    drill:`In a custom, practice the Gravity Well → Recall → Nebula replacement on Ascent A-site. The transition should take under 1 second. Coordinate with your team to push immediately after the Nebula deploys.` },
  { category:'AGENT', agent:'Neon', title:'Neon — Slide Cancel for Stationary Accuracy',
    content:`Cancel your slide (press crouch again mid-slide) just before reaching a corner. The cancel ends your movement instantly, giving you full stationary accuracy at an angle opponents won't expect — they're pre-aiming mid-slide trajectory.\n\nSlide-cancel peeking is Neon's version of Jett's dash peek. It provides the aggression of movement with the accuracy of a stopped shot.`,
    drill:`Custom game: practice the slide-cancel peek around A-main corner on Ascent 30 times. The cancel should happen 0.5m before the corner. Track headshot rate — if you're below 20%, your cancel timing or crosshair placement is off.` },
]

async function main() {
  console.log(`Inserting ${tips.length} Valorant tips into Neon DB...`)
  let ok = 0
  for (const tip of tips) {
    await db.valorantTip.create({ data: tip })
    ok++
    process.stdout.write('.')
  }
  console.log(`\nDone! ${ok}/${tips.length} tips inserted.`)
}

main()
  .catch(e => { console.error(e); process.exit(1) })
  .finally(() => db.$disconnect())
